from .crud_faina import faina
from .crud_faina_member import faina_member
from .crud_faina_role import faina_role
from .crud_note import note
from .crud_team_role import team_role
from .crud_team import team
from .crud_team_colaborator import team_colaborator
from .crud_senior import senior
from .crud_rgm import rgm
from .crud_history import history
from .crud_partner import partner
from .crud_merch import merch
from .crud_note_schoolyear import note_schoolyear
from .crud_note_teacher import note_teacher
from .crud_note_thank import note_thank
from .crud_note_type import note_types
from .crud_note_subject import note_subject
from .crud_user import users
from .crud_video import video
from .crud_video_tag import videotag
from .crud_redirect import redirect
from .crud_news import news
