name: 'Fix Permissions'
description: 'Fix permissions on root-owned files and remove __pycache__ directories before checkout'

runs:
  using: 'composite'
  steps:
    - name: Fix permissions
      shell: bash
      run: |
        set -euo pipefail
        echo "Fixing permissions on root-owned files..."
        # Only run find commands if the current directory exists and has content
        if [ -d . ] && [ -n "$(ls -A . 2>/dev/null)" ]; then
          # Remove __pycache__ directories (they'll be regenerated)
          # Use -depth to process directories bottom-up to avoid errors with subdirectories
          find . -depth -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
          # Fix ownership of any remaining root-owned files (files and directories in single pass)
          find . -user root \( -type f -o -type d \) -exec chown $(whoami):$(whoami) {} + 2>/dev/null || true
        else
          echo "Workspace is empty, skipping permission fixes (will be handled after checkout)"
        fi

