version: "3.9"

services:
  pg_db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes: 
      - pg_data:/var/lib/postgresql/data
  nei_api:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes: 
      - node_modules:/web_app/node_modules
    ports:
      - 8000:8000
    depends_on:
      - pg_db
    stdin_open: true
  # tacaua_api:
  #   build:
  #     context: tacaua-service
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - pg_db
  web_app:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes: 
      - node_modules:/web_app/node_modules
      - ${PWD}/frontend:/web_app
    ports:
      - 3000:3000
    depends_on:
      - nei_api
      # - tacaua_api
    stdin_open: true

volumes:
  pg_data:
    driver: local
  node_modules:
    driver: local
