version: "3.9"
services:
  db_pg:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: postgres_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - ./api-nei/app/db/setup.sql:/docker-entrypoint-initdb.d/setup-nei.sql
      - ./api-rallytascas/app/db/setup.sql:/docker-entrypoint-initdb.d/setup-rallytascas.sql
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: host
    restart: unless-stopped
  api_nei:
    build:
      context: api-nei
    volumes: 
      - ./api-nei:/api_nei
    depends_on:
      db_pg:
        condition: service_healthy
    network_mode: host
    restart: unless-stopped
  api_tacaua:
    build:
      context: api-tacaua
    volumes: 
      - ./api-tacaua:/api_tacaua
    depends_on:
      db_pg:
        condition: service_healthy
    network_mode: host
    restart: unless-stopped
  api_rallytascas:
    build:
      context: api-rallytascas
    volumes: 
      - ./api-rallytascas:/api_rallytascas
    depends_on:
      db_pg:
        condition: service_healthy
    network_mode: host
    restart: unless-stopped
    profiles:
      - disabled
  webapp_nei:
    build:
      context: webapp-nei
    volumes: 
      - node_modules:/webapp_nei/node_modules
      - ./webapp-nei:/webapp_nei
    network_mode: host
    restart: unless-stopped

volumes:
  pg_data:
    driver: local
  node_modules:
    driver: local
