version: "3.9"

services:
  pg_db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes: 
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend_net
    restart: always
  nei_api:
    image: neiaauav/nei-api:${TAG:-latest}
    build:
      context: nei-api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - ROOT_PATH=/nei/api/v1
      - POSTGRES_SERVER=pg_db
    depends_on:
      - pg_db
    networks:
      - backend_net
    restart: always
  tacaua_api:
    image: neiaauav/tacaua-api:${TAG:-latest}
    build:
      context: tacaua-api
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      - ROOT_PATH=/tacaua/api/v1
      - POSTGRES_SERVER=pg_db
    depends_on:
      - pg_db
    networks:
      - backend_net
    restart: always
  rallytascas_api:
    image: neiaauav/rallytascas-api:${TAG:-latest}
    build:
      context: rallytascas-api
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    environment:
      - ROOT_PATH=/rallytascas/api/v1
      - POSTGRES_SERVER=pg_db
    depends_on:
      - pg_db
    networks:
      - backend_net
    restart: always
  web_app:
    image: neiaauav/web-app:${TAG:-latest}
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - nei_api
      - tacaua_api
    networks:
      - frontend_net
    restart: always
  nginx:
    image: neiaauav/nginx:${TAG:-latest}
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /nginx-letsencrypt:/etc/letsencrypt
    depends_on:
      - nei_api
      - tacaua_api
      - web_app
    networks:
      - backend_net
      - frontend_net
    restart: always

networks:
  backend_net:
    driver: bridge
  frontend_net:
    driver: bridge

volumes:
  pg_data:
    driver: local
