FROM python:3.9-slim as requirements-stage

ENV PYTHONUNBUFFERED 1

WORKDIR /nei_api

# RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
# RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
#   --mount=type=cache,target=/var/lib/apt,sharing=locked \
#   apt update && apt-get --no-install-recommends install -y gcc

# TODO: incomplete

RUN apt-get update && apt-get -y install libpq-dev gcc

RUN pip install --upgrade pip \
    pip install --no-cache-dir --upgrade poetry

RUN poetry install

EXPOSE 8000

CMD poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
