version: "3.9"

services:
  web_nei:
    environment:
      ENABLE_GALA: true

  # api_gala:
  #   ...

  web_gala:
    build:
      context: extensions/gala/web-gala
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    volumes:
      - gala_modules:/web_gala/node_modules
      - ./extensions/gala/web-gala:/web_gala
    networks:
      - frontend
    restart: unless-stopped

  proxy:
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/nei.web.ua.pt/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/locations.conf:/etc/nginx/conf.d/locations.conf:ro
      - ./proxy/locations.gala.conf:/etc/nginx/conf.d/locations.gala.conf:ro
    depends_on:
      # - api_gala
      - web_gala


volumes:
  gala_modules:
    driver: local
