from .crud_tacaua_classification import tacaua_classification
from .crud_tacaua_game import tacaua_game
from .crud_tacaua_team import tacaua_team
from .crud_faina import faina
from .crud_faina_member import faina_member
from .crud_faina_roles import faina_roles
from .crud_notes import notes
from .crud_team_roles import team_roles
from .crud_team import team
from .crud_team_colaborators import team_colaborators
from .crud_seniors import seniors
from .crud_seniors_students import seniors_students