version: "3.9"

services:
  api_rally:
    image: neiaauav/api-rally:${TAG:-latest}
    build:
      context: api-rally
      dockerfile: Dockerfile.prod
    ports:
      - 8003:8003
    environment:
      ENV: production
      POSTGRES_SERVER: db_pg
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    volumes: 
      - /api-rally/static:/api_rally/static
    depends_on:
      db_pg:
        condition: service_healthy
    networks:
      - backend
    restart: always

  # web-rally:
  #   ...

  proxy:
    volumes:
      - /proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - /proxy/locations.conf:/etc/nginx/conf.d/locations.conf:ro
      - /proxy/locations.rally.conf:/etc/nginx/conf.d/locations.rally.conf:ro
      - /proxy/nei.web.ua.pt/default.prod.conf:/etc/nginx/conf.d/default.conf
      - /proxy/nei.web.ua.pt/ssl:/etc/ssl/private
    depends_on:
      - api_rally
      # - web_rally
