version: "3.9"

services:
  api_rally:
    build:
      context: extensions/rally/api-rally
    ports:
      - 8003:8003
    environment:
      POSTGRES_SERVER: db_pg
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./extensions/rally/api-rally:/api_rally
    depends_on:
      db_pg:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped
    profiles:
      - rally

  # web-rally:
  #   ...

  proxy:
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/locations.conf:/etc/nginx/conf.d/locations.conf:ro
      - ./proxy/locations.rally.conf:/etc/nginx/conf.d/locations.rally.conf:ro
      - ./proxy/nei.web.ua.pt/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_rally
      # - web_rally
