"""First Commit

Revision ID: 604576647082
Revises: 
Create Date: 2022-06-19 09:40:46.234008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604576647082'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # manually added to create schema
    op.execute(f"create schema if not exists aauav_nei")
    op.create_table('tacaua_modality_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('type', sa.Enum('COLECTIVE', 'INDIVIDUAL', name='type_enum'), nullable=True),
    sa.Column('gender', sa.Enum('MIXED', 'FEMININE', 'MASCULINE', name='gender_enum'), nullable=True),
    sa.Column('pts_victory', sa.SmallInteger(), nullable=True),
    sa.Column('pts_draw', sa.SmallInteger(), nullable=True),
    sa.Column('pts_defeat', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='aauav_nei'
    )
    op.create_table('tacaua_team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='aauav_nei'
    )
    op.create_table('tacaua_game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team1_id', sa.Integer(), nullable=True),
    sa.Column('team2_id', sa.Integer(), nullable=True),
    sa.Column('goals1', sa.SmallInteger(), nullable=True),
    sa.Column('goals2', sa.SmallInteger(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team1_id'], ['aauav_nei.tacaua_team.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['aauav_nei.tacaua_team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='aauav_nei'
    )
    op.create_index(op.f('ix_aauav_nei_tacaua_game_date'), 'tacaua_game', ['date'], unique=False, schema='aauav_nei')
    op.create_index(op.f('ix_aauav_nei_tacaua_game_team1_id'), 'tacaua_game', ['team1_id'], unique=False, schema='aauav_nei')
    op.create_index(op.f('ix_aauav_nei_tacaua_game_team2_id'), 'tacaua_game', ['team2_id'], unique=False, schema='aauav_nei')
    op.create_table('tacaua_modality',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modality_details_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('division', sa.SmallInteger(), nullable=True),
    sa.Column('division_group', sa.String(length=5), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['modality_details_id'], ['aauav_nei.tacaua_modality_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='aauav_nei'
    )
    op.create_index(op.f('ix_aauav_nei_tacaua_modality_year'), 'tacaua_modality', ['year'], unique=False, schema='aauav_nei')
    op.create_table('tacaua_classification',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('modality_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('games', sa.SmallInteger(), nullable=True),
    sa.Column('victories', sa.SmallInteger(), nullable=True),
    sa.Column('draws', sa.SmallInteger(), nullable=True),
    sa.Column('defeats', sa.SmallInteger(), nullable=True),
    sa.Column('g_scored', sa.SmallInteger(), nullable=True),
    sa.Column('g_conceded', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['modality_id'], ['aauav_nei.tacaua_modality.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['aauav_nei.tacaua_team.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'modality_id'),
    schema='aauav_nei'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tacaua_classification', schema='aauav_nei')
    op.drop_index(op.f('ix_aauav_nei_tacaua_modality_year'), table_name='tacaua_modality', schema='aauav_nei')
    op.drop_table('tacaua_modality', schema='aauav_nei')
    op.drop_index(op.f('ix_aauav_nei_tacaua_game_team2_id'), table_name='tacaua_game', schema='aauav_nei')
    op.drop_index(op.f('ix_aauav_nei_tacaua_game_team1_id'), table_name='tacaua_game', schema='aauav_nei')
    op.drop_index(op.f('ix_aauav_nei_tacaua_game_date'), table_name='tacaua_game', schema='aauav_nei')
    op.drop_table('tacaua_game', schema='aauav_nei')
    op.drop_table('tacaua_team', schema='aauav_nei')
    op.drop_table('tacaua_modality_details', schema='aauav_nei')
    # manually added to drop enums and schema
    op.execute(f"drop type if exists type_enum, gender_enum")
    op.execute(f"drop schema if exists aauav_nei")
    # ### end Alembic commands ###
