# gala Extension Routes (enabled)

location ~ ^/(api|static)/gala(/.*)?$ {
    limit_except GET POST PUT DELETE {
        deny all;
    }

    proxy_pass http://api_gala:8004;
}

location ~ ^/gala(/.*)?$ {
    proxy_pass http://web_gala:3002;
}

location = /gala {
    return 301 /gala/;
}
