FROM nginx:1.20-alpine

# Nginx config
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./default.prod.conf /etc/nginx/conf.d/default.conf
COPY ./locations.conf /etc/nginx/conf.d/locations.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
