"""Add JobOffer table

Revision ID: 986d6f972720
Revises: caaa223a3654
Create Date: 2026-05-11 08:02:17.420008

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "986d6f972720"
down_revision = "caaa223a3654"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_offer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("company", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("application_url", sa.String(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_offer")),
        schema="nei",
    )
    op.create_index(
        op.f("ix_nei_job_offer_id"), "job_offer", ["id"], unique=False, schema="nei"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_nei_job_offer_id"), table_name="job_offer", schema="nei")
    op.drop_table("job_offer", schema="nei")
    # ### end Alembic commands ###
