"""Add unique constraint to faina member columns

Revision ID: caaa223a3654
Revises: 9fc0db742749
Create Date: 2024-01-31 14:24:52.263922

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "caaa223a3654"
down_revision = "9fc0db742749"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_faina_member_member_id_faina_id_role_id"),
        "faina_member",
        ["member_id", "faina_id", "role_id"],
        schema="nei",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_faina_member_member_id_faina_id_role_id"),
        "faina_member",
        schema="nei",
        type_="unique",
    )
    # ### end Alembic commands ###
