
from .crud_faina import faina
from .crud_faina_member import faina_member
from .crud_faina_roles import faina_roles
from .crud_notes import notes
from .crud_team_roles import team_roles
from .crud_team import team
from .crud_team_colaborators import team_colaborators
from .crud_seniors import seniors
from .crud_seniors_students import seniors_students
from .crud_rgm import rgm
from .crud_history import history
from .crud_partners import partners
from .crud_merchandisings import merchandisings
from .crud_notes_schoolyear import notes_schoolyear
from .crud_notes_teachers import notes_teachers
from .crud_notes_thanks import notes_thanks
from .crud_notes_types import notes_types
from .crud_notes_subject import notes_subject
from .crud_users import users
from .crud_video import video
from .crud_video_tag import videotag
from .crud_redirect import redirect
from .crud_news import news
