[tool.poetry]
name = "tacaua-service"
version = "0.1.0"
readme = "README.md"
packages = [{include = "tacaua_service"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
