FROM node:16-alpine as build-stage

WORKDIR /webapp_nei

COPY ./package.json ./

COPY ./yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

FROM nginx

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build-stage /webapp_nei/build /usr/share/nginx/html

EXPOSE 3000
