# Import all the models, so that Base has them before being
# imported by Alembic
from app.db.base_class import Base
from app.models.faina_member import FainaMember
from app.models.faina_role import FainaRole
from app.models.faina import Faina
from app.models.history import History
from app.models.merch import Merch
from app.models.news import News
from app.models.note_schoolyear import NoteSchoolYear
from app.models.note_subject import NoteSubject
from app.models.note_teacher import NoteTeacher
from app.models.note_thank import NoteThank
from app.models.note_type import NoteType
from app.models.note import Note
from app.models.partner import Partner
from app.models.redirect import Redirect
from app.models.rgm import Rgm
from app.models.senior_student import SeniorStudent
from app.models.senior import Senior
from app.models.team_colaborator import TeamColaborator
from app.models.team_role import TeamRole
from app.models.team import Team
from app.models.user import User
from app.models.video_tag import VideoTag
from app.models.video import Video
