from typing import List, TYPE_CHECKING

from sqlalchemy import CheckConstraint, String
from sqlalchemy.orm import Mapped, declared_attr, mapped_column, relationship

from app.db.base_class import Base

if TYPE_CHECKING:
    from .team_section import TeamSection


class TeamMandate(Base):
    # Technical key, generated by the database. The human identity is
    # `mandate` ("2026/27"), which is what the public API and the CMS use.
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    mandate: Mapped[str] = mapped_column(
        String(7), unique=True, nullable=False, index=True
    )

    # Directus writes straight to PostgreSQL, so the format is enforced here.
    @declared_attr.directive
    def __table_args__(cls):
        return (
            CheckConstraint(
                "mandate ~ '^[0-9]{4}(/[0-9]{2})?$'", name="mandate_format"
            ),
            Base.__table_args__,
        )

    sections: Mapped[List["TeamSection"]] = relationship(
        "TeamSection",
        back_populates="mandate_ref",
        order_by="TeamSection.weight",
    )
