name: Build and Test api-nei

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/api-nei.yaml'
      - 'api-nei/*'
  pull_request:
    paths:
      - '.github/workflows/api-nei.yaml'
      - 'api-nei/*'
  workflow_dispatch:

jobs:
  api-nei:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres_test
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository files
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ^3.10

      - name: Install poetry
        run: |
          pip install --upgrade pip setuptools
          pip install -U poetry

      - name: Install system libraries
        run: sudo apt-get -y install libpq-dev gcc

      - name: Install dependencies
        working-directory: ./api-nei
        run: poetry install --no-interaction --no-root

      - name: Run tests
        working-directory: ./api-nei
        run: poetry run pytest
