name: Deploy

on:
  workflow_dispatch:
    inputs:
      extension:
        description: 'Deploy with extension'
        required: false
        type: choice
        options: 
        - ''
        - gala
        - rally
      copy_compose:
        description: 'Copy compose files to server'
        required: false
        type: boolean

jobs:
  copy:
    runs-on: self-hosted
    if: ${{ github.event.inputs.copy_compose == 'true' }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup variables
      id: variables
      run: |
        export TAG=${GITHUB_SHA::7}
        echo "sources=compose.prod.yml" >> $GITHUB_OUTPUT
        echo "targets=~/deploys/${TAG}/" >> $GITHUB_OUTPUT
        if [[ -n "${{ github.event.inputs.extension }}" ]]; then
          mv extensions/${{ github.event.inputs.extension }}/compose.override.prod.yml compose.${{ github.event.inputs.extension }}.prod.yml
          echo "sources=compose.prod.yml,compose.${{ github.event.inputs.extension }}.prod.yml" >> $GITHUB_OUTPUT
        fi
    - name: Copy compose files
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "${{ steps.variables.outputs.sources }}"
        target: "${{ steps.variables.outputs.targets }}"
        timeout: 100s

  build:
    runs-on: ubuntu-latest
    env:
      PRODUCTION: true
      COMPOSE_PROFILES: ${{ github.event.inputs.profiles }}
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u neiaauav -p $DOCKER_PASSWORD
    - name: Build docker images
      run: |
        make ${{ github.event.inputs.extension }} build
    - name: Push docker images
      run: |
        make ${{ github.event.inputs.extension }} push FLAGS="--ignore-push-failures"
    - name: Push docker images with tag
      run: |
        export TAG=${GITHUB_SHA::7}
        make ${{ github.event.inputs.extension }} build
        make ${{ github.event.inputs.extension }} push FLAGS="--ignore-push-failures"
  
  deploy:
    needs: build
    runs-on: self-hosted
    env:
      PRODUCTION: true
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      EMAIL_SENDER_ADDRESS: ${{ secrets.EMAIL_SENDER_ADDRESS }}
      EMAIL_SMTP_HOST: ${{ secrets.EMAIL_SMTP_HOST }}
      EMAIL_SMTP_PASSWORD: ${{ secrets.EMAIL_SMTP_PASSWORD }}
      EMAIL_SMTP_USER: ${{ secrets.EMAIL_SMTP_USER }}
      IDP_SECRET_KEY: ${{ secrets.IDP_SECRET_KEY }}
      RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
    steps:
    - uses: actions/checkout@v3    
    - name: Deploy with docker-compose
      run: |
        docker stop $(docker ps -aq) || true
        docker rm $(docker ps -aq) || true
        docker image prune -af
        docker builder prune
        make ${{ github.event.inputs.extension }} pull
        make ${{ github.event.inputs.extension }} up FLAGS="-d --remove-orphans --force-recreate"
