name: Push and Deploy

on:
  push:
    branches:
      - deploy

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u neiaauav -p $DOCKER_PASSWORD
    - name: Build docker images
      run: |
        docker-compose -f docker-compose.prod.yaml build
    - name: Push docker images
      run: |
        docker-compose -f docker-compose.prod.yaml push --ignore-push-failures
    - name: Push docker images with tag
      run: |
        export TAG=${GITHUB_SHA:0:7}
        docker-compose -f docker-compose.prod.yaml build
        docker-compose -f docker-compose.prod.yaml push --ignore-push-failures
  
  deploy:
    needs: build
    runs-on: self-hosted
    timeout-minutes: 5
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      EMAIL_SENDER_ADDRESS: ${{ secrets.EMAIL_SENDER_ADDRESS }}
      EMAIL_SMTP_HOST: ${{ secrets.EMAIL_SMTP_HOST }}
      EMAIL_SMTP_PASSWORD: ${{ secrets.EMAIL_SMTP_PASSWORD }}
      EMAIL_SMTP_USER: ${{ secrets.EMAIL_SMTP_USER }}
      IDP_SECRET_KEY: ${{ secrets.IDP_SECRET_KEY }}
      RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Copy docker-compose file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "docker-compose.prod.yaml,docker-compose.prod.yaml"
        target: "~/deploy-latest/,~/deploy-${GITHUB_SHA:0:7}/"
    - name: Deploy with docker-compose
      run: |
        docker stop $(docker ps -aq) || true
        docker rm $(docker ps -aq) || true
        docker image prune -af
        docker builder prune
        docker-compose -f docker-compose.prod.yaml pull
        docker-compose -f docker-compose.prod.yaml up -d --remove-orphans --force-recreate
