name: Test api-rally

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/api-rally.yaml'
      - 'extensions/rally/api-rally/**/*'
  pull_request:
    paths:
      - '.github/workflows/api-rally.yaml'
      - 'extensions/rally/api-rally/**/*'
  workflow_dispatch:

jobs:
  api-rally:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres_test
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository files
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry
        run: |
          pip install --upgrade pip setuptools
          pip install -U poetry

      - name: Install system libraries
        run: sudo apt-get -y install libpq-dev gcc

      - name: Install dependencies
        working-directory: ./extensions/rally/api-rally
        run: poetry install --no-interaction --no-root --with test,dev

      - name: Format
        if: '!cancelled()'
        working-directory: ./extensions/rally/api-rally
        run: poetry run black --check --diff app

      - name: Lint
        if: '!cancelled()'
        working-directory: ./extensions/rally/api-rally
        run: poetry run flake8 .

      - name: Type-Check
        if: '!cancelled()'
        working-directory: ./extensions/rally/api-rally
        run: poetry run mypy app --strict

      - name: Run tests
        if: '!cancelled()'
        working-directory: ./extensions/rally/api-rally
        run: poetry run pytest
